baseURL = "http://example.org/"
languageCode = "en-us"
title = "Brian's Portfolio"
theme = "basic"
[params]
 author = "Brian Hogan"
 description = "My portfolio site"
 googleAnalytics = "UA-12345678"
 gh_url = "https://api.github.com/users"
 gh_user = "zhandosweb"
